services:
  - type: web
    name: learning-management-server
    env: node
    plan: free
    root: Server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: PORT
        value: 8000
